# Generated by Django 6.0.4 on 2026-04-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho', models.CharField(max_length=50)),
                ('chave_ssh', models.TextField(blank=True, null=True)),
                ('ip_flutuante', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(default='Construindo', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
